More efficient retrieval of JIRA ticket information

diff --git a/git-jira b/git-jira
--- a/git-jira
+++ b/git-jira
@@ -7,13 +7,13 @@ function usage() {
 	log "Usage:"
 	log -e "\tgit jira setup <JIRA endpoint> <JIRA project key>"
 	log -e "OR"
+	log -e "\tgit jira info <JIRA ticket key> [<JIRA ticket key> ...]"
+	log -e "OR"
 	log -e "\tgit jira url <JIRA ticket key>"
 	log -e "OR"
-	log -e "\tgit jira resolution <JIRA ticket key>"
-	log -e "OR"
-	log -e "\tgit jira summary <JIRA ticket key>"
-	log -e "OR"
 	log -e "\tgit jira translate-branch-name"
+	log -e "OR"
+	log -e "\tgit jira info-from-branch-name"
 	log -e "OR"
 	log -e "\tgit jira extract-ticket-keys"
 	abort
@@ -23,18 +23,18 @@ function setup_first() {
 	abort "Use 'git jira setup <JIRA endpoint> <JIRA project key>' to set the JIRA settings first."
 }
 
-function query_ticket() {
-	local TICKET_KEY
-	TICKET_KEY="$1"
-	local URL
-	URL="$ENDPOINT/rest/api/2/issue/$TICKET_KEY?fields=id,key,resolution,summary"
-	curl -s -X GET -L -f -H "Content-Type: application/json" "$URL" \
-		|| abort "Failed to retrieve ticket '$TICKET_KEY' from '$URL'"
+function query_tickets() {
+	declare -a ticket_keys
+	readarray ticket_keys
+	curl -s -f -X POST -L -H "Content-Type: application/json" \
+		--data "{\"jql\": \"key IN ($(join_by ',' ${ticket_keys[*]}))\", \"fields\": [\"key\",\"resolution\",\"summary\"], \"maxResults\": ${#ticket_keys[@]}}" \
+		"$ENDPOINT/rest/api/2/search" \
+		| jq '.issues[] | {key: .key, summary: .fields.summary, resolution: .fields.resolution.name}' \
+		|| abort "Failed to retrieve some tickets in '${ticket_keys[*]}'; are they all valid ticket keys?"
 }
 
 function extract_field() {
-	which jq 1>/dev/null || abort "You must install the JSON parsing utility 'jq' first."
-	jq -er "$1" || abort "Failed to extract field '$1' from the JIRA ticket."
+	jq -r "${@}" || abort "Failed to extract fields '${@}' from the JIRA ticket."
 }
 
 if [ "$1" = 'setup' ]
@@ -56,24 +56,31 @@ then
 	(( $# == 1 )) || usage
 	TICKET_KEY="$1"
 	echo "$ENDPOINT/browse/$TICKET_KEY"
-elif [ "$1" = 'resolution' ]
+elif [ "$1" = 'info' ]
 then
 	shift
-	(( $# == 1 )) || usage
-	TICKET_KEY="$1"
-	query_ticket "$TICKET_KEY" | extract_field '.fields.resolution.name'
-elif [ "$1" = 'summary' ]
-then
-	shift
-	(( $# == 1 )) || usage
-	TICKET_KEY="$1"
-	query_ticket "$TICKET_KEY" | extract_field '.fields.summary'
+	if (( $# > 0 ))
+	then
+		join_by $'\n' "${@}" | query_tickets
+	else
+		query_tickets
+	fi
 elif [ "$1" = 'translate-branch-name' ]
 then
 	shift
 	(( $# == 0 )) || usage
-	# Output: <input><tab><ticket name><tab><base branch (if any)>
+	# Output: <input><tab><ticket key><tab><base branch (if any)>
 	sed -r 's/^('"$PROJECT_KEY"'-[[:digit:]]+)(-(([.[:digit:]]+)|.*))?$/\0\t\1\t\4/;t;d;'
+elif [ "$1" = 'info-from-branch-name' ]
+then
+	shift
+	(( $# == 0 )) || usage
+	TSV=$(mktemp)
+	sed -r 's/^('"$PROJECT_KEY"'-[[:digit:]]+)(-(([.[:digit:]]+)|.*))?$/\0\t\1\t\4/;t;d;' | sort -t $'\t' -k 2 >$TSV
+	cut -f 2 -d $'\t' $TSV | query_tickets | jq -r '[.key, .summary, .resolution] | @tsv' | sort -t $'\t' -k 1 \
+			| join -t $'\t' -1 2 -2 1 "$TSV" - \
+			| jq --raw-input 'split("\t") | {key: .[0], branch: .[1], base_branch: .[2], summary: .[3], resolution: .[4]}'
+	rm -f "$TSV"
 elif [ "$1" = 'extract-ticket-keys' ]
 then
 	shift
